Rename Common Lisp and Assembly implementations

diff --git a/test b/test
--- a/test
+++ b/test
@@ -47,17 +47,20 @@ if [ $1 == "all" ]; then
   exit 0
 fi
 
-cd $1 || exit 1
+cd $1 || {
+  echo "Error: directory $1 not found."
+  exit 1
+}
 
 case $1 in
   apl) wget -q -nc https://raw.githubusercontent.com/ngn/apl/f31f06/lib/apl.js && \
        chmod +x apl.js && \
        test_suite test1 ./apl.js quicksort.apl
        ;;
-  assembly) nasm -g -f elf quicksort.asm && \
-            gcc -m32 -o quicksort quicksort.o && \
-            test_suite test1 ./quicksort
-            ;;
+  asm32) nasm -g -f elf quicksort.asm && \
+         gcc -m32 -o quicksort quicksort.o && \
+         test_suite test1 ./quicksort
+         ;;
   bash) test_suite test1 bash quicksort.sh
         ;;
   bash-pipes) test_suite test1 bash quicksort.sh
@@ -67,6 +70,8 @@ case $1 in
      ;;
   clojure) test_suite test1 clojure quicksort.clj
            ;;
+  commonlisp) test_suite test1 clisp quicksort.lisp
+              ;;
   c#) mcs Quicksort.cs && \
       test_suite test1 mono Quicksort.exe
       ;;
@@ -110,8 +115,6 @@ case $1 in
   kotlin) kotlinc quicksort.kt && \
           test_suite test1 kotlin QuicksortKt
           ;;
-  lisp) test_suite test1 clisp quicksort.lisp
-        ;;
   lua) test_suite test1 lua quicksort.lua
        ;;
   nim) nim c --hints=off --verbosity=0 --nimcache=/tmp/nim quicksort.nim && \
@@ -155,4 +158,6 @@ case $1 in
   vb.net) vbnc -nologo -quiet Quicksort.vb && \
           test_suite test1 mono Quicksort.exe
           ;;
+  *) echo "Error: no runner implementation for $1 was defined."
+     ;;
 esac
